### ISSUE TITLE
关于安装脚本中的错误。

### ISSUE THREAD

**Issue by Popeye9869** [PenExtMods/ydpExt#1]
![Screenshot_2023-12-09-21-08-37-578_bin.mt.plus.jpg](https://github.com/DSFdsfWxp/ydpExt/assets/137862090/2077adab-e89b-4392-b6df-3c43227a62b9)

第13行似乎多了一个点.
27行uninstall少打一个s

**Comment by Popeye9869** [comment]
native模式的安装脚本中

**Comment by DSFdsfWxp** [comment]
感谢反馈，已修复
